version: '3'

services:

  app:
    container_name: app
    build: app
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    volumes:
      - ./app:/app
      - /var/log/app:/var/log/app

  mongo:
    image: mongo
    container_name: quizz_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - quizz_db-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

volumes:
  quizz_db-data:
